### ISSUE TITLE
404 Error on link "Fit Assessment"  samples 

### ISSUE THREAD

**Issue by eyalyaron** [GoogleCloudPlatform/migrate-for-anthos-gke#10]
Getting 404 error when clicking on 
'GoogleCloudPlatform/migrate-to-containers' repository doesn't contain the 'examples/fit-assessment' path in 'main'.  
![image](https://user-images.githubusercontent.com/50546509/198287911-8ed0e4d5-c36a-497b-a648-e00c45953ecd.png)

**Comment by eitaneib** [comment]
Item removed
