### ISSUE TITLE
m2c and mcdc sources

### ISSUE THREAD

**Issue by fzk273** [GoogleCloudPlatform/migrate-for-anthos-gke#17]
Hi! i tried your cli tools for migration and they are working perfectly. id like to add some migration profiles by myself, but i cannot find sources for m2c and mcdc can you please share links?

**Comment by barp** [comment]
Hi,
Thanks for being interested in M2C and MCDC, I would like to confirm what you want to do.
Do you want to add a new plugin, for example like apache/websphere/jboss/tomcat those would be plugins.
Or do you want to extend one of the existing plugins (apache/websphere/jboss/tomcat).
Or something else?

Currently we don't have links for the source but depending on interest this might change.

Thanks.

**Comment by fzk273** [comment]
i was thinking about extending functionality for existing tomcat plugin and i have some thoughts about how to migrate python apps with your tool, but until i will totally understand how it works, i wont be able to write this plugin and integrate it with m2c and mcdc.

**Comment by barp** [comment]
Unfortunately, we're not able to provide the source for the m2c and mcdc migration profiles at this time. However, we encourage you to open an issue or a for a feature request.

We currently have plans to document the contract between the plugins and the m2c/mcdc tools to allow extending custom plugins and also on releasing the plugins themselves as open-source but this will take some time (current estimate is early 2024)

In the meantime, we're always looking for ways to improve if you want to contact us directly with more details feel free to email us at: m2c-feedback-external@google.com

Thanks

**Comment by danaradg** [comment]
Closing for now. Please reopen if there's interest in 3rd party extensions for M2C.
